# Generated by Django 3.0.8 on 2020-08-16 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='static/song/thumbnail')),
                ('audio', models.FileField(upload_to='static/song/audio')),
                ('lyric', models.TextField()),
                ('timeline', models.TextField()),
                ('photos', models.TextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('like', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='static/song/images')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
        ),
    ]
