# Generated by Django 3.0.8 on 2020-08-01 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('audio', models.FileField(upload_to='aac/')),
                ('lyric', models.TextField()),
                ('timeline', models.TextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
